general_settings:
  master_key: os.environ/PROXY_MASTER_KEY

model_list:
  - model_name: whisреr-сlоud
    litellm_params:
      model: openai/openai/whisper-large-v3
      custom_llm_provider: openai
      api_key: os.environ/CLOUD_API_KEY
      api_base: https://foundation-models.api.cloud.ru/v1
      response_format: json
      timeout: 120
    model_info:
      mode: audio_transcription
      input_cost_per_second: 0.00015

  - model_name: whisper-nexara
    litellm_params:
      model: whisper-1
      custom_llm_provider: openai
      api_key: os.environ/NEXARA_API_KEY
      api_base: https://api.nexara.ru/v1
      timeout: 120
    model_info:
      mode: audio_transcription
      input_cost_per_second: 0.000008

router_settings:
  fallbacks:
    - whisper-cloud: ["whisper-nexara"]
  num_retries: 2

litellm_settings:
  cache: false
  cache_params:
    type: redis
    namespace: "litellm.caching.caching"